# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "word_transformer.Word" do
    optional :word, :string, 1
  end
  add_message "word_transformer.Result" do
    optional :result, :string, 1
  end
end

module WordTransformer
  Word = Google::Protobuf::DescriptorPool.generated_pool.lookup("word_transformer.Word").msgclass
  Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("word_transformer.Result").msgclass
end
