apiVersion: extensions/v1beta1

kind: Deployment

metadata:
  name: reverse-dep

spec:
  replicas: 3

  template:

    metadata:
      labels:
        name: reverse-pods

    spec:
      containers:
      - image: micro-reverse:1.0
        name: reverse-container