apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apigateway-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: apigateway-pods
    spec:
      containers:
      - image: micro-apigateway:1.0
        name: apigateway-container
        env:
        - name: UPPER_CASE_URL
          value: uppercase-svc
        - name: LOWER_CASE_URL
          value: lowercase-svc
        - name: REVERSE_URL
          value: reverse-svc
        - name: TITLE_CASE_URL
          value: titlecase-svc