apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-pods
    spec:
      containers:
      - image: micro-apigateway:v1
        name: nginx-container